on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit black isort clang-format
          pip install -U setuptools
          pip install nanobind
          pip install numpy
          sudo apt-get install libblas-dev liblapack-dev liblapacke-dev
      - name: Setup upterm session 
        uses: lhotari/action-upterm@v1
